/**
 * The bridge from tags to shows.
 *
 * Tagging the files is only half the job — Navidrome still has to be told that
 * `artistcountry` exists, and someone still has to write a smart playlist per language.
 * Both are fiddly and easy to get subtly wrong, so babeltag generates them.
 */
import type { TagKind } from './core/types.ts';
import { countryName, languageName } from './core/iso.ts';
import { COUNTRY_TAG, LANGUAGE_TAG, navidromeAliases } from './tags/formats.ts';

/** The field name a smart playlist refers to — Navidrome's lowercase tag name. */
export const COUNTRY_FIELD = COUNTRY_TAG.toLowerCase();
export const LANGUAGE_FIELD = LANGUAGE_TAG.toLowerCase();

export interface SmartPlaylist {
  name: string;
  comment: string;
  all: Array<Record<string, Record<string, string>>>;
  sort: string;
  order: 'asc' | 'desc';
}

/** Build one `.nsp` smart playlist selecting a single country or language. */
export function buildPlaylist(kind: TagKind, code: string): SmartPlaylist {
  const field = kind === 'country' ? COUNTRY_FIELD : LANGUAGE_FIELD;
  const label = kind === 'country' ? countryName(code) : languageName(code);
  return {
    name: label,
    comment: `Generated by babeltag — every track where ${field} is ${code}.`,
    all: [{ is: { [field]: code } }],
    sort: 'artist',
    order: 'asc',
  };
}

/** A filename safe on every platform, derived from the playlist label. */
export function playlistFileName(kind: TagKind, code: string): string {
  const label = kind === 'country' ? countryName(code) : languageName(code);
  const safe = label.replace(/[^\p{L}\p{N} _-]/gu, '').trim().replace(/\s+/g, '-');
  const prefix = kind === 'country' ? 'country' : 'language';
  return `${prefix}-${safe || code}.nsp`;
}

/**
 * The `navidrome.toml` block that makes the country tag visible.
 *
 * Language needs nothing: Navidrome already maps `language` (and `tlan`, and the iTunes
 * freeform atom) out of the box. Country is genuinely custom, and every per-format
 * spelling has to be listed because Navidrome matches raw keys and does not normalise
 * across formats.
 */
export function configSnippet(): string {
  const aliases = navidromeAliases('country')
    .map((alias) => JSON.stringify(alias))
    .join(', ');
  return [
    '# --- babeltag: add to your navidrome.toml -------------------------------',
    '# Makes ARTISTCOUNTRY visible to Navidrome and usable in smart playlists.',
    '# LANGUAGE needs no configuration - Navidrome already reads it.',
    `Tags.${COUNTRY_FIELD}.Aliases = [${aliases}]`,
    '# ------------------------------------------------------------------------',
    '#',
    '# After adding this you MUST run a FULL scan. A quick scan will not pick up',
    '# tag-configuration changes, and the new tag will silently stay invisible.',
  ].join('\n');
}
